### PR TITLE
chore: use 1 azure credentials instead of 3 string credentials

### PR DESCRIPTION
**Pull request by lemeurherve**
Followup of https://github.com/jenkins-infra/packer-images/pull/185 to close https://github.com/jenkins-infra/packer-images/issues/183

Tested with a replay here: https://infra.ci.jenkins.io/blue/organizations/jenkins/packer-images/detail/main/106/pipeline/304

### CODE REVIEW

**Comment by lemeurherve** [comment]
These string credentials don't seem to be used elsewhere, I propose we delete them after the merge of this PR.
image

**Review by dduportal — APPROVED** [review]

**Review by timja — APPROVED** [review]
why not use

**Comment by lemeurherve** [comment]
> why not use

WDYM? The previous values?

**Review by timja — APPROVED** [review]

**Comment by timja** [comment]
> > why not use
> 
> WDYM? The previous values?

unintentional, I was thinking about the declarative support, but I see you wanted specific names

**Pull request merged**
