### PR TITLE
feat: add a 1909 azure image

### PR DESCRIPTION
**Pull request by garethjevans**

### CODE REVIEW

**Comment by garethjevans** [comment]
Build output shows
```
    azure-arm: Major  Minor  Build  Revision
    azure-arm: -----  -----  -----  --------
    azure-arm: 10     0      18363  0
```

**Comment by garethjevans** [comment]
@slide I think this gets us the correct image on Azure - for some reason I can't add you as a reviewer

**Review by markyjackson-taulia — APPROVED** [review]

**Review by olblak — APPROVED** [review]

**Review by MarkEWaite — APPROVED** [review]
Looks good to me.  Optional change proposed to take the newest versions

**Comment by slide** [comment]
Do we need a separate image from the other? I think we can just move to this and update the normal windows 2019 agent file.

**Review by slide — CHANGES_REQUESTED** [review]
We need a Windows Server 2019 with Container support for this. We want to be able to build newer docker images than we can with the current images.

**Comment by garethjevans** [comment]
@slide there is a `datacenter-core-1909-with-containers-smalldisk`/`MicrosoftWindowsServer` base image we could use?

**Comment by slide** [comment]
That was what I was going to look at for this purpose.

**Comment by garethjevans** [comment]
Ok, I'll give that a go in an hour or so and amend the PR

**Review by timja — APPROVED** [review]

**Review by slide — APPROVED** [review]

**Review by markyjackson-taulia — APPROVED** [review]

**Pull request merged**
