### PR TITLE
chore: use windows 2004 as the base image for azure

### PR DESCRIPTION
**Pull request by garethjevans**

### CODE REVIEW

**Review by markyjackson-taulia — APPROVED** [review]
Not sure of CI is needed for this job.

**Comment by slide** [comment]
FYI, the 1909 smalldisk image was having issues building the docker containers for 1809 and other non-1909 images.

**Comment by garethjevans** [comment]
@slide Thanks, I'll take a look - have you got an example of the docker build that's having issues so I've got something to test with?

**Comment by slide** [comment]
@garethjevans I believe this is one: https://ci.jenkins.io/job/Packaging/job/docker/job/PR-989/115/

**Pull request merged**
