### PR TITLE
chore: ensure that spot instances are used for packer builds

### PR DESCRIPTION
**Pull request by dduportal**
As per https://github.com/jenkins-infra/helpdesk/issues/3502 and https://github.com/jenkins-infra/helpdesk/issues/3485, cloud cost control is important for us.

The goal of this PR is to ensure that packer VM used to build VM templates are always using Spot prices on both AWS EC2 and Azure.

### CODE REVIEW

**Review by timja — APPROVED** [review]

**Review by smerle33 — APPROVED** [review]
LGTM

**Review by smerle33 — CHANGES_REQUESTED** [review]
there is an error with the spot

**Comment by dduportal** [comment]
Weird, it points to the `spot = true` in the `azure-arm`  source, which I got from https://developer.hashicorp.com/packer/plugins/builders/azure/arm#spot .

I might be mis-reading the doc, lemme try locally

**Comment by dduportal** [comment]
Oh I see, there documentation is incomplete: https://github.com/hashicorp/packer-plugin-azure/blob/79cd1eab80ead3910cf7507ef8355766c816818d/builder/azure/arm/config_test.go#L2644-L2646

**Comment by dduportal** [comment]
Opened a PR on their doc: https://github.com/hashicorp/packer-plugin-azure/pull/293

**Comment by dduportal** [comment]
- AWS spot problem reproduced locally 
- We are hitting https://github.com/hashicorp/packer-plugin-amazon/issues/198 
- Adding the `spot_price` atrribute explictly set to `auto` allows me to spin up an EC2 `arm64` VM, so let's try this on the CI now

**Pull request merged**
