### PR TITLE
feat: add tfsec (v1.28.0) on all platforms

### PR DESCRIPTION
**Pull request by Kevin-CB**
For https://github.com/jenkins-infra/packer-images/issues/198

This PR add `tfsec` on all platforms

Not sure if I had to add an yml file on the updatecli

### CODE REVIEW

**Comment by dduportal** [comment]
- Just triggered a build (as your code looks good to me!). Let's see if it works as expected (I'm not sure for linux-arm64)

> Not sure if I had to add an yml file on the updatecli

Usually, we do a subsequent PR (separation of concerns) . Don't worry on this.

**Comment by dduportal** [comment]
The Windows builds are failing because tfsec 1.28.0 does not exist on chocolatey: https://community.chocolatey.org/packages?q=tfsec (only 1.22.1 as for today :'( ).

Could you either:
- Use direct download, for Windows, of the tfsec binary from their GitHub release page (such as https://github.com/aquasecurity/tfsec/releases/tag/v1.28.0) ?
- Remove the Windows part (and we'll add it later)?

**Comment by lemeurherve** [comment]
Or we wait a little for https://github.com/aquasecurity/tfsec-chocolatey/pull/8 🙂

**Comment by dduportal** [comment]
Given the time it takes to the chocolatey maintainer to update this recipe (and it seems to be the same for most of the chocolatey packages such as git, vagrant, packer, etc.), I feel like we should go with the binary installation instead. WDYT @lemeurherve @Kevin-CB ?

**Comment by Kevin-CB** [comment]
Yeah you're right, I'll work on that when time permits 🙂

**Comment by dduportal** [comment]
Gentle ping 🧸

**Pull request closed without merging**
