### PR TITLE
Use Adoptium JDK 8u302-b08 and JDK11 11.0.12+7 [INFRA-3048]

### LINKED ISSUE #77: JDK 8u292 can break plugin tests that use the Java Keystore
JDK 8u292 inadvertently removed the PBEWithSHA1AndDESede Keystore algorithm. This can break plugin tests that use the Java Keystore.

When those tests run with the Jenkins JDK8 configuration on on ci.jenkins.io, errors will be seen like:

    java.security.KeyStoreException: Key protection  algorithm not found: java.security.UnrecoverableKeyException: Encrypt Private Key failed: unrecognized algorithm name: PBEWithSHA1AndDESede

So we need to either upgrade or downgrade the JDK8 version on ci.jenkins.io to address this.

### PR DESCRIPTION
**Pull request by chriskilding**
Fixes #77

### CODE REVIEW

**Comment by chriskilding** [comment]
Looks like 8u302-b08 has dropped in AdoptOpenJDK so Windows should be fine.

But I believe Ubuntu is still shipping 8u292 so if this was merged it wouldn't actually work yet... https://packages.ubuntu.com/focal-updates/openjdk-8-jdk

**Comment by dduportal** [comment]
I'm also in favor of switching the Ubuntu installation from package to binary image.
Are you feeling to do it in this PR @chriskilding?

**Comment by chriskilding** [comment]
I guess if we switched to the AdoptOpenJDK package for Ubuntu we'd want to use their deb repos for it (https://adoptopenjdk.jfrog.io/ui/native/deb/pool/main/a/adoptopenjdk-8-hotspot).

I've looked at the repos and it looks like they don't have an 8u302 package there either.

Looks like we're not *quite* there yet... better to wait it out I think, at least till Adopt puts 8u302 in their deb repo.

**Comment by dduportal** [comment]
Sounds good, let's wait.

Thanks for this contribution @chriskilding!

**Comment by chriskilding** [comment]
Here's the catch...

I messaged the AdoptOpenJDK (now Adoptium) project to ask if they could release a new build for 8u302: https://github.com/adoptium/installer/issues/342

Unfortunately they've picked this moment to rebuild their packaging infrastructure now that AdoptOpenJDK is becoming Adoptium, which means no new AdoptOpenJDK builds (at least for Linux) until that is done.

I also emailed the Ubuntu dev mailing list about upgrading the vanilla `openjdk-8-jdk` build they use. No response yet.

This leaves our plugins with broken Keystore-related tests and no upgrade solution for the foreseeable future.

**Comment by chriskilding** [comment]
So a couple of options:

- Downgrade the package we use to the previous working OpenJDK version.
- Use a different JDK distribution which _has_ packaged 8u302.

**Comment by timja** [comment]
I assume you want to do something like:
https://github.com/jenkinsci/docker/pull/1185

(haven't checked if they've got packages available but they should be)

**Comment by dduportal** [comment]
@chriskilding are you able to add the `useAci: true` attribute in your pipeline, so you can use the new Temurin JDK that @timja mentionned?

**Comment by chriskilding** [comment]
I gave`useAci: true` a go in a noddy PR:

https://github.com/jenkinsci/aws-secrets-manager-credentials-provider-plugin/pull/115

Oddly the JDK 8 suite is shown as passing but the overall build fails.

**Comment by chriskilding** [comment]
Aha... is Docker available in the ACI environment? The build is failing because docker-maven-plugin can't connect to Docker.

**Comment by dduportal** [comment]
> Aha... is Docker available in the ACI environment? The build is failing because docker-maven-plugin can't connect to Docker.

Oh my bad, you are in the case where a VM is required for agent (instead of a container). It meanse that there are no docker provided. Sorry for wasting your time on this. You can rollback, but thanks for testing.

We'll have to find a way to install temurin's JDK on these package image templates

**Comment by chriskilding** [comment]
Yep that plugin needs Docker access to run Moto (an AWS mock written in Python) for some integration tests.

Is there an ETA on how long it would take to add Temerin's JDK to the full VM image templates?

**Comment by dduportal** [comment]
Expect end of the week to a general availability on ci.jenkins.io:

* Today (Tuesday) and tomorrow (Wednesday) are weekly/LTS release days
* We need to switch the JDK installation from Ubuntu's native OpenJDK package to binary distribution from Eclipse Temurin (https://adoptium.net/releases.html?variant=openjdk8&jvmVariant=hotspot), this make need some back and forth

If you are interested in helping, it could help of course :) I'm available to pair, mentor (or implement)

**Comment by chriskilding** [comment]
End of week is cool with me. I'd be happy to try any changes out on my plugins if that would help though.

**Comment by dduportal** [comment]
OK: 2 commits added:
- Bumped OpenJDK 11 to 11.0.12+7 (only version supported on Adoptium as for today)
- Switched the installation to OpenJDK's Adoptium project

**Review by olblak — APPROVED** [review]
While I didn't test it manually, this pull request sounds good to me be

**Comment by dduportal** [comment]
Oh crap, I clicked the auto-merge button thinking it was another PR

**Comment by chriskilding** [comment]
Saw that you merged this (accidentally) - does this mean the changes are good to go in the next image rebuild, or is more work needed?

**Comment by dduportal** [comment]
@chriskilding we are waiting for today's Jenkins releases to be finished before updating ci.jenkins.io to use the latest template with Elcipse Temurin within. I'll mention you here once it's ready to go.

**Comment by dduportal** [comment]
@chriskilding once https://github.com/jenkins-infra/jenkins-infra/pull/1848 is merged, then the change will be applied to ci.jenkins.io automatically and both VMs and tools installations for ci.jenkins.io would be updated.

**Comment by dduportal** [comment]
@chriskilding Adoptium is now generally used on ci.jenkins.io, you can start your tests.

Incoming messages on dev list and discourse.

**Comment by timja** [comment]
@dduportal https://ci.jenkins.io/blue/organizations/jenkins/Infra%2Frepository-permissions-updater/detail/PR-2065/1/pipeline/

**Comment by dduportal** [comment]
@timja should be fixed by https://github.com/jenkins-infra/jenkins-infra/pull/1849

**Comment by chriskilding** [comment]
Alas I'm seeing a build error on agents with the new Temurin JDK 8:

```
09:24:05  + mvn --batch-mode --show-version --errors --no-transfer-progress --update-snapshots -Dmaven.repo.local=/home/jenkins/workspace/edentials-provider-plugin_PR-123@tmp/m2repo -Dmaven.test.failure.ignore -Dspotbugs.failOnError=false -Dcheckstyle.failOnViolation=false -Dcheckstyle.failsOnError=false -Penable-jacoco -Dset.changelist help:evaluate -Dexpression=changelist -Doutput=/home/jenkins/workspace/edentials-provider-plugin_PR-123@tmp/changelist clean install
09:24:05  /lib64/ld-linux-x86-64.so.2: No such file or directory
```

Any ideas what would cause that?

**Comment by MarkEWaite** [comment]
> Alas I'm seeing a build error on agents with the new Temurin JDK 8:
> 
> ```
> 09:24:05  + mvn --batch-mode --show-version --errors --no-transfer-progress --update-snapshots -Dmaven.repo.local=/home/jenkins/workspace/edentials-provider-plugin_PR-123@tmp/m2repo -Dmaven.test.failure.ignore -Dspotbugs.failOnError=false -Dcheckstyle.failOnViolation=false -Dcheckstyle.failsOnError=false -Penable-jacoco -Dset.changelist help:evaluate -Dexpression=changelist -Doutput=/home/jenkins/workspace/edentials-provider-plugin_PR-123@tmp/changelist clean install
> 09:24:05  /lib64/ld-linux-x86-64.so.2: No such file or directory
> ```
> 
> Any ideas what would cause that?

That [build](https://ci.jenkins.io/job/Plugins/job/aws-secrets-manager-credentials-provider-plugin/view/change-requests/job/PR-123/1/) was run on an ARM64 instance but then tried to install the AMD64 Java tool.  I suspect there is either a label configuration error or a tool configuration error that is causing the AMD64 Java 8 tool to be installed on an ARM64 agent.

I assume it was a temporary flaw in the labeling of the agents after a configuration change.  Let us know if you see it again.

**Comment by timja** [comment]
build is green now

**Comment by chriskilding** [comment]
The ARM flaw is back again today - have seen it a couple of times on builds this morning.

**Comment by timja** [comment]
> The ARM flaw is back again today - have seen it a couple of times on builds this morning.

Link?

**Comment by chriskilding** [comment]
https://ci.jenkins.io/job/Plugins/job/aws-secrets-manager-secret-source-plugin/job/PR-9/3/console

**Comment by chriskilding** [comment]
https://ci.jenkins.io/job/Plugins/job/aws-secrets-manager-credentials-provider-plugin/job/PR-96/13/console

**Comment by timja** [comment]
Weird it should be using https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.12+7/OpenJDK11U-jdk_x64_linux_hotspot_11.0.12_7.tar.gz as far as I can tell from the jdk11 tool

**Comment by chriskilding** [comment]
And another one...

https://ci.jenkins.io/blue/organizations/jenkins/Plugins%2Faws-secrets-manager-credentials-provider-plugin/detail/PR-96/15/pipeline

**Comment by chriskilding** [comment]
I'm thinking I should probably file a new issue about this - is packer-images the appropriate place for it?

**Comment by timja** [comment]
> I'm thinking I should probably file a new issue about this - is packer-images the appropriate place for it?

yes

**Comment by chriskilding** [comment]
Ok - moving here: https://github.com/jenkins-infra/packer-images/issues/87

**Pull request merged**
