### PR TITLE
breaking: bump from Ubuntu 20.04 to Ubuntu 22.04

### PR DESCRIPTION
**Pull request by lemeurherve**
Fixes https://github.com/jenkins-infra/packer-images/issues/300

Created the following VM image definitions in portal.azure.com:

<details>
<summary>Details</summary>

image

image

image

</details>

Note: some of the VM image definitions are located in `eastus2` instead of `eastus`.

### CODE REVIEW

**Comment by lemeurherve** [comment]
Bummer: it seems the only available 22.04 canonical image available for now on Azure is not free: https://ubuntu.com/azure

```
$ az vm image list-skus --offer 0001-com-ubuntu-server-focal --location eastus --publisher canonical --output table
Location    Name
----------  ---------------
eastus      20_04-lts
eastus      20_04-lts-arm64
eastus      20_04-lts-gen2
```

**Comment by lemeurherve** [comment]
Related: https://github.com/jenkins-infra/helpdesk/issues/2982

**Comment by timja** [comment]
> $0.002/hour / $18 p.a

May be okay though

**Comment by lemeurherve** [comment]
More price details from [Azure Marketplace](https://azuremarketplace.microsoft.com/en-gb/marketplace/apps/canonical.0001-com-ubuntu-pro-jammy?tab=PlansAndPrice):

image

cc @dduportal FYI

**Comment by lemeurherve** [comment]
Even on the bigger VMs the software cost goes up to $54 per year, not that bad.

**Comment by dduportal** [comment]
Gotta check the overost because we have to count all hours of VMs for all controllers (ci.j, trusted.j, etc.).

Sounds like the Ubuntu 22.04 is almost there for AKS as per https://azure.microsoft.com/en-us/updates/generally-available-aks-support-for-ubuntu-2204/: I propose we wait a bit unless we have a strict requirement forcing us to upgrade to 22.04.
I assume that Microsoft have a lot of technical reasons including cgroupsv2 support (with their hypervisor thing).


Alternatively: Is there a reason for not using a Debian base, like we do with the Jenkins official Docker images? By doing so, the tools installations would be closer and the effort would be shared (I'm thinking installing a reent git version ofr instance).

WDYT?


=> Let's put this topic on the next team meeting, the 8 of Nov.

**Comment by lemeurherve** [comment]
> Bummer: it seems the only available 22.04 canonical image available for now on Azure is not free: [ubuntu.com/azure](https://ubuntu.com/azure)
> 
> ```
> $ az vm image list-skus --offer 0001-com-ubuntu-server-focal --location eastus --publisher canonical --output table
> Location    Name
> ----------  ---------------
> eastus      20_04-lts
> eastus      20_04-lts-arm64
> eastus      20_04-lts-gen2
> ```

I used the wrong offer 😓 
```
$ az vm image list-skus --offer 0001-com-ubuntu-server-jammy --location eastus --publisher canonical --output table
Location    Name
----------  ---------------
eastus      22_04-lts
eastus      22_04-lts-arm64
eastus      22_04-lts-gen2
```

**Comment by lemeurherve** [comment]
22.04 available, now failing because of a gpg-agent error:
```
[2022-11-30T14:59:10.610Z] 2022-11-30T14:59:10Z: ==> docker.ubuntu: + add-apt-repository --yes ppa:phd/chromium-browser
[2022-11-30T14:59:13.203Z] 2022-11-30T14:59:13Z: ==> docker.ubuntu: gpg: error running '/usr/bin/gpg-agent': probably not installed
[2022-11-30T14:59:13.203Z] 2022-11-30T14:59:13Z: ==> docker.ubuntu: gpg: failed to start agent '/usr/bin/gpg-agent': Configuration error
[2022-11-30T14:59:13.203Z] 2022-11-30T14:59:13Z: ==> docker.ubuntu: gpg: can't connect to the agent: Configuration error
[2022-11-30T14:59:13.203Z] 2022-11-30T14:59:13Z: ==> docker.ubuntu: Traceback (most recent call last):
[2022-11-30T14:59:13.203Z] 2022-11-30T14:59:13Z: ==> docker.ubuntu:   File "/usr/lib/python3/dist-packages/softwareproperties/shortcuthandler.py", line 423, in add_key
[2022-11-30T14:59:13.203Z] 2022-11-30T14:59:13Z: ==> docker.ubuntu:     subprocess.run(cmd.split(), check=True, input=keys)
[2022-11-30T14:59:13.203Z] 2022-11-30T14:59:13Z:     docker.ubuntu: Repository: 'deb https://ppa.launchpadcontent.net/phd/chromium-browser/ubuntu/ jammy main'
[2022-11-30T14:59:13.203Z] 2022-11-30T14:59:13Z:     docker.ubuntu: Description:
[2022-11-30T14:59:13.203Z] 2022-11-30T14:59:13Z: ==> docker.ubuntu:   File "/usr/lib/python3.10/subprocess.py", line 524, in run
[2022-11-30T14:59:13.203Z] 2022-11-30T14:59:13Z:     docker.ubuntu: Chromium Browser - latest official stable build
[2022-11-30T14:59:13.203Z] 2022-11-30T14:59:13Z: ==> docker.ubuntu:     raise CalledProcessError(retcode, process.args,
[2022-11-30T14:59:13.203Z] 2022-11-30T14:59:13Z:     docker.ubuntu:
[2022-11-30T14:59:13.203Z] 2022-11-30T14:59:13Z: ==> docker.ubuntu: subprocess.CalledProcessError: Command '['gpg', '-q', '--no-options', '--no-default-keyring', '--batch', '--keyring', '/etc/apt/trusted.gpg.d/phd-ubuntu-chromium-browser.gpg', '--homedir', '/tmp/tmp_rxblvpb', '--import']' returned non-zero exit status 2.
```

**Comment by dduportal** [comment]
We can resume the work on this image (when we'll have enough bandwidth): no more blocker.

Adding the "breaking" label to ensure it will bump the major digit number

**Comment by dduportal** [comment]
Blocked by #563 #564

**Pull request merged**
